In [1]:
import pandas as pd
import numpy as np
import pyproj
import folium

# 관악구_단란주점


In [5]:
df = pd.read_csv('중구_단란주점.csv',encoding='cp949')
df.head()


개방자치단체코드                    관리번호 영업상태명   소재지면적 소재지우편번호  \
0   3010000  3010000-103-1976-02299    폐업  256.18  100864   
1   3010000  3010000-103-1976-02314    폐업  113.88  100070   
2   3010000  3010000-103-1979-02001    폐업   38.60  100880   
3   3010000  3010000-103-1980-02315    폐업   20.62  100021   
4   3010000  3010000-103-1987-02266    폐업   56.38  100282   

                     지번주소 도로명주소 도로명우편번호       사업장명      좌표정보(X)      좌표정보(Y)  
0  서울특별시 중구 태평로2가 23-0번지    NaN     NaN       갤러리바  197979.0212  451376.7834  
1    서울특별시 중구 소공동 87-1번지    NaN     NaN  나인스게이트칵텔바  198172.1511  451350.9692  
2  서울특별시 중구 흥인동 112-34번지    NaN     NaN         목마          NaN          NaN  
3    서울특별시 중구 명동1가 6-0번지    NaN     NaN  로얄호텔 양주점빠          NaN          NaN  
4  서울특별시 중구 인현동2가 73-1번지    NaN     NaN     연가단란주점  199550.5063  451392.2197

In [29]:
df['좌표정보(X)'] = pd.to_numeric(df['좌표정보(X)'],errors='coerce')
df['좌표정보(Y)'] = pd.to_numeric(df['좌표정보(Y)'],errors='coerce')

In [30]:
def project_array(coord, p1_type, p2_type):
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]
    

In [31]:
coord = np.array(df[['좌표정보(X)','좌표정보(Y)']])
coord

array([[191182.00048053, 442181.79189008],
       [192250.2377978 , 442720.8852356 ],
       [192767.45420818, 440299.37614939],
       [191679.93220392, 442057.78372871],
       [191210.00657717, 442171.32347337],
       [195328.99690753, 442754.35842242],
       [193441.64194001, 442464.26687253],
       [193648.94205156, 442932.14319635],
       [193579.5378954 , 442899.97002096],
       [191583.35405151, 442197.10657129],
       [194548.65169234, 442330.32431138],
       [191524.46791285, 442121.92978237],
       [191627.67097363, 442343.32787061],
       [195652.99036302, 442258.3417342 ],
       [195048.37671378, 442241.2905453 ],
       [194719.32655052, 442351.24248363],
       [193571.70509425, 443057.19523181],
       [193522.13853576, 442996.34493152],
       [192377.35459811, 442824.00755877],
       [195034.26888764, 442243.05276851],
       [195921.03322775, 442003.94910641],
       [193547.48118771, 442986.21394523],
       [197932.05277482, 441549.55787775],
       [195

In [32]:
p1_type = "epsg:2097"
p2_type = "epsg:4326"
result = project_array(coord, p1_type, p2_type)
result

c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\Hamin\AppData\Local\Temp\ipykernel_7792\3986416653.py:4: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas

array([[126.89820131,  37.48178356],
       [126.9102732 ,  37.48665044],
       [126.91614526,  37.46483683],
       [126.90383239,  37.4806709 ],
       [126.89851808,  37.48168951],
       [126.94508405,  37.48697294],
       [126.92374653,  37.48434761],
       [126.92608629,  37.48856464],
       [126.92530182,  37.48827428],
       [126.90273888,  37.48192532],
       [126.93626394,  37.48314806],
       [126.90207398,  37.48124743],
       [126.90323826,  37.48324317],
       [126.94875039,  37.48250542],
       [126.9419146 ,  37.48234871],
       [126.9381935 ,  37.48333753],
       [126.92521186,  37.48969082],
       [126.92465194,  37.48914221],
       [126.91170941,  37.48758064],
       [126.94175508,  37.48236451],
       [126.95178237,  37.48021458],
       [126.92493858,  37.48905111],
       [126.97452004,  37.47612734],
       [126.95178649,  37.48329737],
       [126.90838527,  37.48090422],
       [126.90429717,  37.483014  ],
       [126.93443828,  37.48503101],
 

In [33]:
result=pd.DataFrame(result,columns=['경도','위도'])
result

경도         위도
0   126.898201  37.481784
1   126.910273  37.486650
2   126.916145  37.464837
3   126.903832  37.480671
4   126.898518  37.481690
..         ...        ...
73  126.925676  37.483453
74  126.925038  37.483695
75  126.950504  37.481350
76  126.909998  37.481829
77  126.911207  37.482931

[78 rows x 2 columns]

In [34]:
danran = pd.read_excel('관악구_단란주점.xlsx')
danran['경도']=result['경도']
danran['위도']=result['위도']
danran.to_excel('관악구_단란주점.xlsx')


In [35]:
danran.head()

Unnamed: 0.1  Unnamed: 0  개방자치단체코드  영업상태코드  영업상태명   소재지면적  \
0             0          29   3200000       1  영업/정상   67.50   
1             1          30   3200000       1  영업/정상  108.81   
2             2          47   3200000       1  영업/정상   93.84   
3             3          49   3200000       1  영업/정상  133.95   
4             4          63   3200000       1  영업/정상  146.47   

                     지번주소                          도로명주소    사업장명  \
0   서울특별시 관악구 신림동 1666번지              서울특별시 관악구 시흥대로 548    8768   
1  서울특별시 관악구 신림동 518-2번지                서울특별시 관악구 신사로 94    8701   
2     서울특별시 관악구 신림동 681-8        서울특별시 관악구 난곡로 103 (신림동)  쎈스노래노래   
3  서울특별시 관악구 신림동 566-7번지   서울특별시 관악구 남부순환로 지하 1405 (신림동)   황실메들리   
4   서울특별시 관악구 신림동 1655-43       서울특별시 관악구 조원로2길 48 (신림동)  오케이노래바   

                 업태구분명        좌표정보(X)        좌표정보(Y)          경도         위도  
0  2019-11-10 02:40:00  191182.000481  442181.791890  126.898201  37.481784  
1  2018-08-31 23:59:59  192250.237798  442720.885236  126.910273  37.486650  
2                 단란주점  192767.454208  440299.376149  126.916145  37.464837  
3                 단란주점  191679.932204  442057.783729  126.903832  37.480671  
4                 단란주점  191210.006577  442171.323473  126.898518  37.481690

# 관악구_유흥업소


In [36]:
df = pd.read_excel('관악구_유흥업소.xlsx')
df.head()

Unnamed: 0  개방자치단체코드                    관리번호  영업상태명 상세영업상태명  소재지면적  \
0          11   3200000  3200000-102-2000-10195  영업/정상      영업  96.25   
1          12   3200000  3200000-102-2000-10592  영업/정상      영업  73.67   
2          19   3200000  3200000-102-2007-00004  영업/정상      영업  82.52   
3          33   3200000  3200000-102-2010-00006  영업/정상      영업  83.34   
4          34   3200000  3200000-102-2004-00007  영업/정상      영업  56.56   

                             지번주소                               도로명주소  \
0           서울특별시 관악구 남현동 1061-22            서울특별시 관악구 과천대로 945 (남현동)   
1            서울특별시 관악구 신림동 1431-1       서울특별시 관악구 신림로 373, 지하1층 (신림동)   
2  서울특별시 관악구 봉천동 857-5 외 1필지 지하1층  서울특별시 관악구 관악로 174 (봉천동,외 1필지 지하1층)   
3           서울특별시 관악구 신림동 1431-16       서울특별시 관악구 신림로 359, 지하1층 (신림동)   
4           서울특별시 관악구 신림동 1422-20   서울특별시 관악구 남부순환로181길 6 (신림동, 지하1층)   

       사업장명    업태구분명        좌표정보(X)        좌표정보(Y)    구    동  
0         수      룸살롱  198284.487350  441422.547539  관악구  남현동  
1     썸씽노래빠      룸살롱  193610.378561  442802.923555  관악구  신림동  
2     텔미노래바  비어(바)살롱  195766.887002  442051.412687  관악구  봉천동  
3  야구장 노래클럽      룸살롱  193657.227469  442684.677287  관악구  신림동  
4       스머프      룸살롱  193838.005723  442520.948016  관악구  신림동

In [37]:
df['좌표정보(X)'] = pd.to_numeric(df['좌표정보(X)'],errors='coerce')
df['좌표정보(Y)'] = pd.to_numeric(df['좌표정보(Y)'],errors='coerce')

In [38]:
coord = np.array(df[['좌표정보(X)','좌표정보(Y)']])
coord

array([[198284.4873505 , 441422.54753911],
       [193610.37856083, 442802.92355539],
       [195766.88700161, 442051.41268675],
       [193657.22746921, 442684.67728681],
       [193838.00572287, 442520.94801648],
       [193563.62433033, 442402.74846178],
       [193671.1809231 , 442608.25698059],
       [193612.24935301, 442364.88431511],
       [193551.23568979, 442377.41467675],
       [193696.42754964, 442721.31539019],
       [193767.93540735, 442617.37610285],
       [193630.48864525, 442347.33298494],
       [192431.8660287 , 442261.66854858],
       [195829.40904396, 442222.78687025],
       [191307.75110839, 442331.0970665 ],
       [193606.51542593, 442399.58995187],
       [193480.72644155, 442387.81087858],
       [192393.66331082, 442281.96435867],
       [193636.16751907, 442688.22950769],
       [193611.4407628 , 442378.04009547],
       [193611.4407628 , 442378.04009547],
       [193549.63516581, 442401.40362892],
       [193715.72094663, 442661.60059249],
       [193

In [39]:
p1_type = "epsg:2097"
p2_type = "epsg:4326"
result = project_array(coord, p1_type, p2_type)
result

c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\Hamin\AppData\Local\Temp\ipykernel_7792\3986416653.py:4: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas

array([[126.97850472,  37.47498372],
       [126.92565138,  37.4874001 ],
       [126.95003933,  37.48064153],
       [126.92618213,  37.48633503],
       [126.92822754,  37.48486107],
       [126.92512627,  37.4837942 ],
       [126.92634056,  37.48564658],
       [126.92567637,  37.48345338],
       [126.92498642,  37.48356585],
       [126.92662504,  37.48666541],
       [126.92743446,  37.48572941],
       [126.92588275,  37.48329537],
       [126.9123316 ,  37.48251441],
       [126.95074522,  37.4821859 ],
       [126.89962129,  37.48313   ],
       [126.92561124,  37.48376604],
       [126.92418912,  37.48365902],
       [126.91189946,  37.48269696],
       [126.92594398,  37.48636689],
       [126.92566712,  37.48357191],
       [126.92566712,  37.48357191],
       [126.92496811,  37.48378198],
       [126.9268437 ,  37.48612751],
       [126.92630239,  37.4857675 ],
       [126.92847107,  37.48477181],
       [126.92570996,  37.48731978],
       [126.92743738,  37.48597724],
 

In [40]:
result=pd.DataFrame(result,columns=['경도','위도'])
result

경도         위도
0    126.978505  37.474984
1    126.925651  37.487400
2    126.950039  37.480642
3    126.926182  37.486335
4    126.928228  37.484861
..          ...        ...
400  126.950291  37.480700
401  126.975800  37.475978
402  126.899758  37.483228
403  126.950504  37.481350
404  126.912121  37.480462

[405 rows x 2 columns]

In [41]:
uh = pd.read_excel('관악구_유흥업소.xlsx')
uh['경도']=result['경도']
uh['위도']=result['위도']
uh.to_excel('관악구_유흥업소.xlsx')

# 관악구_숙박업소

In [42]:
df = pd.read_excel('관악구_숙박업소.xlsx')

In [43]:
df['좌표정보(X)'] = pd.to_numeric(df['좌표정보(X)'],errors='coerce')
df['좌표정보(Y)'] = pd.to_numeric(df['좌표정보(Y)'],errors='coerce')
coord = np.array(df[['좌표정보(X)','좌표정보(Y)']])
coord

array([[195635.9007707 , 441952.94150102],
       [193796.49992064, 442525.99298378],
       [193491.94580789, 442478.79031553],
       [193608.44765448, 442632.12005209],
       [193500.13472055, 442488.63097619],
       [195636.857061  , 441997.82629268],
       [194026.31222844, 440938.38982527],
       [198252.08755221, 441329.73739805],
       [193629.77184108, 442701.73405953],
       [192582.7339417 , 442560.59262553],
       [193769.4580079 , 442681.55309225],
       [193973.52387044, 441047.59300442],
       [198219.95764891, 441490.43590941],
       [193620.50095524, 442568.3947366 ],
       [193889.47297725, 442534.15825806],
       [193566.47292725, 442660.99022836],
       [193605.26672379, 442676.20398958],
       [198234.19591119, 441552.00329613],
       [195663.54158788, 441874.43464061],
       [193622.70514351, 442683.01476769],
       [192409.81926399, 442132.08997146],
       [192440.64050602, 441861.0516926 ],
       [192623.33169108, 442274.53656618],
       [193

In [44]:
p1_type = "epsg:2097"
p2_type = "epsg:4326"
result = project_array(coord, p1_type, p2_type)
result

c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
c:\Users\Hamin\AppData\Local\Programs\Python\Python39\lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\Hamin\AppData\Local\Temp\ipykernel_7792\3986416653.py:4: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas

array([[126.948559  ,  37.47975368],
       [126.92775821,  37.48490624],
       [126.92431516,  37.48447883],
       [126.92563105,  37.48586115],
       [126.92440766,  37.48456755],
       [126.94856955,  37.4801581 ],
       [126.93036961,  37.47060344],
       [126.97813867,  37.47414743],
       [126.92587155,  37.48648852],
       [126.91403431,  37.48520895],
       [126.92745113,  37.48630765],
       [126.92977197,  37.47158702],
       [126.97777504,  37.47559526],
       [126.92576789,  37.48528707],
       [126.92880935,  37.48498043],
       [126.9251562 ,  37.48612098],
       [126.9255947 ,  37.48625832],
       [126.97793585,  37.47615002],
       [126.94887197,  37.47904647],
       [126.92579181,  37.48631981],
       [126.91208368,  37.48134673],
       [126.91243495,  37.47890493],
       [126.91449622,  37.48263192],
       [126.92496733,  37.48695573],
       [126.92500346,  37.4868787 ],
       [126.91224566,  37.48137826],
       [126.92600406,  37.48585573],
 

In [45]:
result=pd.DataFrame(result,columns=['경도','위도'])
result

경도         위도
0    126.948559  37.479754
1    126.927758  37.484906
2    126.924315  37.484479
3    126.925631  37.485861
4    126.924408  37.484568
..          ...        ...
409  126.926084  37.483791
410  126.925988  37.483822
411  126.952339  37.483166
412  126.951215  37.484661
413  126.936753  37.471176

[414 rows x 2 columns]

In [46]:
sb = pd.read_excel('관악구_숙박업소.xlsx')
sb['경도']=result['경도']
sb['위도']=result['위도']
sb.to_excel('관악구_숙박업소.xlsx')