In [37]:
import pandas as pd
import PublicDataReader as pdr

df = pd.read_excel('중구_노드_링크_네트워크데이터.xlsx')
df = df.loc[(df['읍면동코드']>1114000000)&(df['읍면동코드']<1117000000),:]
# pop = pd.read_excel('중구_인구데이터.xlsx')
# pop = pop.iloc[:,:4]
# pop.drop('시간대구분',inplace=True,axis=1)
# pop.head()


In [51]:
연결정보 = pdr.code_hdong_bdong()
연결정보 = 연결정보.loc[(연결정보['시군구코드']=='11140'),:]
연결정보[['법정동코드','행정동코드']]=연결정보[['법정동코드','행정동코드']].astype(int)
연결정보 = 연결정보.loc[(연결정보['행정동코드']>1114000000),:]
연결정보.head(50)

출처: 행정기관(행정동) 및 관할구역(법정동) 변경내역(2023. 7. 3. 시행)


시도코드    시도명  시군구코드 시군구명       행정동코드     읍면동명       법정동코드     동리명  \
156   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010100     무교동   
157   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010200      다동   
158   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010300   태평로1가   
159   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010400   을지로1가   
160   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010500   을지로2가   
161   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010600  남대문로1가   
162   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010700     삼각동   
163   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010800     수하동   
164   11  서울특별시  11140   중구  1114051000   태평로1가동  1114010900     장교동   
165   11  서울특별시  11140   중구  1114051000   태평로1가동  1114011000     수표동   
166   11  서울특별시  11140   중구  1114051000   태평로1가동  1114011500  남대문로2가   
167   11  서울특별시  11140   중구  1114052000      소공동  1114011100     소공동   
168   11  서울특별시  11140   중구  1114052000      소공동  1114011300     북창동   
169   11  서울특별시  11140   중구  1114052000      소공동  1114011400   태평로2가   
170   11  서울특별시  11140   중구  1114052000      소공동  1114011500  남대문로2가   
171   11  서울특별시  11140   중구  1114052000      소공동  1114011600  남대문로3가   
172   11  서울특별시  11140   중구  1114052000      소공동  1114011700  남대문로4가   
173   11  서울특별시  11140   중구  1114052000      소공동  1114011900   봉래동1가   
174   11  서울특별시  11140   중구  1114052000      소공동  1114016600    서소문동   
175   11  서울특별시  11140   중구  1114052000      소공동  1114016700      정동   
176   11  서울특별시  11140   중구  1114052000      소공동  1114016800     순화동   
177   11  서울특별시  11140   중구  1114052000      소공동  1114016900   의주로1가   
178   11  서울특별시  11140   중구  1114052000      소공동  1114017000   충정로1가   
179   11  서울특별시  11140   중구  1114053000  남대문로5가동  1114011800  남대문로5가   
180   11  서울특별시  11140   중구  1114053000  남대문로5가동  1114011900   봉래동1가   
181   11  서울특별시  11140   중구  1114053000  남대문로5가동  1114012000   봉래동2가   
182   11  서울특별시  11140   중구  1114053000  남대문로5가동  1114016800     순화동   
183   11  서울특별시  11140   중구  1114054000      회현동  1114011200     남창동   
184   11  서울특별시  11140   중구  1114054000      회현동  1114011600  남대문로3가   
185   11  서울특별시  11140   중구  1114054000      회현동  1114011700  남대문로4가   
186   11  서울특별시  11140   중구  1114054000      회현동  1114011800  남대문로5가   
187   11  서울특별시  11140   중구  1114054000      회현동  1114011900   봉래동1가   
188   11  서울특별시  11140   중구  1114054000      회현동  1114012000   봉래동2가   
189   11  서울특별시  11140   중구  1114054000      회현동  1114012100   회현동1가   
190   11  서울특별시  11140   중구  1114054000      회현동  1114012200   회현동2가   
191   11  서울특별시  11140   중구  1114054000      회현동  1114012300   회현동3가   
192   11  서울특별시  11140   중구  1114054000      회현동  1114012400   충무로1가   
193   11  서울특별시  11140   중구  1114054000      회현동  1114016800     순화동   
194   11  서울특별시  11140   중구  1114055000       명동  1114010100     무교동   
195   11  서울특별시  11140   중구  1114055000       명동  1114010200      다동   
196   11  서울특별시  11140   중구  1114055000       명동  1114010300   태평로1가   
197   11  서울특별시  11140   중구  1114055000       명동  1114010400   을지로1가   
198   11  서울특별시  11140   중구  1114055000       명동  1114010500   을지로2가   
199   11  서울특별시  11140   중구  1114055000       명동  1114010600  남대문로1가   
200   11  서울특별시  11140   중구  1114055000       명동  1114010700     삼각동   
201   11  서울특별시  11140   중구  1114055000       명동  1114010800     수하동   
202   11  서울특별시  11140   중구  1114055000       명동  1114010900     장교동   
203   11  서울특별시  11140   중구  1114055000       명동  1114011000     수표동   
204   11  서울특별시  11140   중구  1114055000       명동  1114011500  남대문로2가   
205   11  서울특별시  11140   중구  1114055000       명동  1114012100   회현동1가   

         생성일자      말소일자  
156  19880423  19980914  
157  19880423  19980914  
158  19880423  19980914  
159  19880423  19980914  
160  19880423  19980914  
161  19880423  19980914  
162  19880423  19980914  
163  19880423  19980914  
164  19880423  19980914  
165  19880423  19980914  
166  19920416  19980914  
167  19880423      

In [41]:
import numpy as np

In [48]:
연결정보['행정동코드'].unique()

array([1114051000, 1114052000, 1114053000, 1114054000, 1114055000,
       1114056000, 1114057000, 1114058000, 1114059000, 1114060000,
       1114060500, 1114061000, 1114061500, 1114062000, 1114062500,
       1114063000, 1114063500, 1114064000, 1114064500, 1114065000,
       1114066000, 1114066500, 1114067000, 1114068000])

In [45]:
code = [11140520, 11140540, 11140550, 11140570, 11140580, 11140590,
       11140605, 11140615, 11140625, 11140635, 11140645, 11140650,
       11140665, 11140670, 11140680]
len(code)

15

In [54]:
df['읍면동코드'].unique()

array([1114015200, 1114016300, 1114016500, 1114011800, 1114017100,
       1114016200, 1114012400, 1114014800, 1114014400, 1114014900,
       1114012000, 1114010500, 1114014300, 1114014700, 1114016700,
       1114017000, 1114015600, 1114014500, 1114017400, 1114014600,
       1114012100, 1114015500, 1114013200, 1114011500, 1114013400,
       1114016800, 1114011200, 1114011900, 1114013800, 1114016000,
       1114012200, 1114017300, 1114010300, 1114016600, 1114012300,
       1114012600, 1114015000, 1114013100, 1114015400, 1114015700,
       1114013500, 1114012500, 1114015300, 1114014200, 1114015100,
       1114013900, 1114011100, 1114013000, 1114010100, 1114012700,
       1114010800, 1114012900, 1114013700, 1114016400, 1114010600,
       1114012800, 1114015900, 1114013300, 1114014000, 1114010700,
       1114010900, 1114014100, 1114011300, 1114011400, 1114016100,
       1114013600, 1114016900, 1114010200, 1114011600, 1114011000,
       1114017200, 1114015800, 1114011700, 1114010400], dtype=

In [43]:
df['행정동코드'] = np.NaN


In [55]:
## 1114052000
df.loc[df['읍면동코드']==1114011100,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011300,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011400,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011500,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011600,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011700,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114011900,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114016600,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114016700,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114016800,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114016900,'행정동코드'] = 1114052000/100
df.loc[df['읍면동코드']==1114017000,'행정동코드'] = 1114052000/100

## 1114054000
df.loc[df['읍면동코드']==1114011200,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114011600,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114011700,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114011800,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114011900,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114012000,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114012100,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114012200,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114012400,'행정동코드'] = 1114054000/100
df.loc[df['읍면동코드']==1114016800,'행정동코드'] = 1114054000/100

## 1114055000
df.loc[df['읍면동코드']==1114010100,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010200,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010300,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010400,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010500,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010600,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010700,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010800,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114010900,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114011000,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114011500,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012100,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012200,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012300,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012400,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012500,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012600,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012700,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012800,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114012900,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114013000,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114013100,'행정동코드'] = 1114055000/100
df.loc[df['읍면동코드']==1114014200,'행정동코드'] = 1114055000/100


## 1114057000
df.loc[df['읍면동코드']==1114013200,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114013300,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114013600,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114013700,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114013800,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114013900,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114014000,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114014100,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114014200,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114014400,'행정동코드'] = 1114057000/100
df.loc[df['읍면동코드']==1114015800,'행정동코드'] = 1114057000/100

## 1114058000
df.loc[df['읍면동코드']==1114013600,'행정동코드'] = 1114058000/100
df.loc[df['읍면동코드']==1114014300,'행정동코드'] = 1114058000/100
df.loc[df['읍면동코드']==1114014300,'행정동코드'] = 1114058000/100

## 1114059000
df.loc[df['읍면동코드']==1114013200,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114013300,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114013400,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114013500,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114014500,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114014600,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114014700,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114014800,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114014900,'행정동코드'] = 1114059000/100
df.loc[df['읍면동코드']==1114015400,'행정동코드'] = 1114059000/100

## 1114060500
df.loc[df['읍면동코드']==1114015000,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015100,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==111401520,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015300,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015500,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015600,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015700,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114015900,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114016000,'행정동코드'] = 1114060500/100
df.loc[df['읍면동코드']==1114016100,'행정동코드'] = 1114060500/100

## 1114061500
df.loc[df['읍면동코드']==1114016200,'행정동코드'] = 1114061500/100
df.loc[df['읍면동코드']==1114016200,'행정동코드'] = 1114061500/100
df.loc[df['읍면동코드']==1114016400,'행정동코드'] = 1114061500/100

## 1114067000 
df.loc[df['읍면동코드']==1114016500,'행정동코드'] = 1114067000/100

## 1114068000 
df.loc[df['읍면동코드']==1114017100,'행정동코드'] = 1114068000/100
df.loc[df['읍면동코드']==1114017200,'행정동코드'] = 1114068000/100
df.loc[df['읍면동코드']==1114017300,'행정동코드'] = 1114068000/100
df.loc[df['읍면동코드']==1114017400,'행정동코드'] = 1114068000/100



In [59]:
df.columns

Index(['노드링크 유형', '노드 WKT', '노드 ID', '노드 유형 코드', '링크 WKT', '링크 ID', '링크 유형 코드',
       '시작노드 ID', '종료노드 ID', '링크 길이', '시군구코드', '시군구명', '읍면동코드', '읍면동명', '고가도로',
       '지하철네트워크', '교량', '터널', '육교', '횡단보도', '공원,녹지', '건물내', '행정동코드'],
      dtype='object')

In [61]:
df.loc[df['행정동코드'].isnull(),'읍면동코드'].unique()

array([1114015200, 1114016300], dtype=int64)

In [62]:
## 1114015200 1114060500 
df.loc[df['읍면동코드']==1114015200,'행정동코드'] = 1114060500/100
## 1114016300 1114061500
df.loc[df['읍면동코드']==1114016300,'행정동코드'] = 1114061500/100


In [64]:
df['행정동코드'] = df['행정동코드'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13586 entries, 0 to 13621
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   노드링크 유형   13586 non-null  object 
 1   노드 WKT    5823 non-null   object 
 2   노드 ID     13586 non-null  int64  
 3   노드 유형 코드  5823 non-null   float64
 4   링크 WKT    7763 non-null   object 
 5   링크 ID     13586 non-null  int64  
 6   링크 유형 코드  7763 non-null   float64
 7   시작노드 ID   7763 non-null   float64
 8   종료노드 ID   7763 non-null   float64
 9   링크 길이     7763 non-null   float64
 10  시군구코드     13586 non-null  int64  
 11  시군구명      13586 non-null  object 
 12  읍면동코드     13586 non-null  int64  
 13  읍면동명      13586 non-null  object 
 14  고가도로      7763 non-null   float64
 15  지하철네트워크   7763 non-null   float64
 16  교량        7763 non-null   float64
 17  터널        7763 non-null   float64
 18  육교        13586 non-null  int64  
 19  횡단보도      13586 non-null  int64  
 20  공원,녹지     7763 non-null   float64

In [65]:
df.to_excel('중구_노드_링크_네트워크데이터.xlsx')
